title: Scala Nothing To Prod test
category: WIX
sub-Category: Server Guild

tags:
  - Wix
  - Server Onboarding
  - Academy Learning Original

description:
  - content: course-details.md

sections:
  - title: Nothing To Prod
    steps:
      - title: Step 1 - Setup Scala development environment
        content: courses/example-course/01-first-step.md
      - title: Step 2 - Clone repository
        content: courses/example-course/02-second-step.md
      - title: Step 3 - Generate Scala Nile project
        content: courses/example-course/03-third-step.md
      - title: Step 4 - Get your code to master branch
        content: courses/example-course/04-fourth-step.md
      - title: Step 5 - Get your code to production
        content: courses/example-course/05-fifth-step.md
